### ISSUE TITLE
Paginate function: First Page, Last Page emoji

### ISSUE THREAD

**Issue by avurro** [ygimenez/Pagination-Utils#11]
**Is your feature request related to a problem? Please describe.**
In case of more pages will be usefull if user can go fast to last or first page.

**Describe the solution you'd like**
Adding an emoji as ⏩ to go last page and ⏪ to go first page.

**Comment by avurro** [comment]
If possible, making it optional is better

**Comment by ygimenez** [comment]
Feature implemented in [release 2.1.1](https://github.com/ygimenez/Pagination-Utils/tree/2.1.1)
