### ISSUE TITLE
Pagination doesn't work with custom emojis

### ISSUE THREAD

**Issue by avurro** [ygimenez/Pagination-Utils#14]
```java
Paginator paginator = PaginatorBuilder.createPaginator().setHandler(jda)
     .shouldRemoveOnReact(false)
     .setEmote(Emote.SKIP_BACKWARD,":ss:807633784434327563")
     .setEmote(Emote.PREVIOUS,":s_:807633784521621534")
     .setEmote(Emote.SKIP_FORWARD,":dd:807633784580997130") 
     .setEmote(Emote.NEXT,":d_:807633784571822100")
     .build();
```
Result:
![image](https://user-images.githubusercontent.com/2487392/107122738-ca678900-6899-11eb-91c6-7d75cc758f62.png)

With default emoji it works.

**Comment by ygimenez** [comment]
That's not how you use custom emojis, the correct mention will always be `<:name:id>` for static emotes and `<:a:name:id>` for animated emotes (this is a Discord thing, not a library's).

EDIT: in the case of the library, you must pass only the ID of the emote, omitting the name.

**Comment by avurro** [comment]
from javadoc:
![image](https://user-images.githubusercontent.com/2487392/107205354-103d6200-69fe-11eb-923e-c35575e0ab1e.png)
Using format that you suggest i get the following error:
`java.lang.NumberFormatException: The specified ID is not a valid snowflake`

**Comment by ygimenez** [comment]
Found the issue, it was previously only checking for emote names regardless of type, now it'll check for either name or ID depending on whether it's an emoji or Emote.

Please update to [version 2.1.2](https://github.com/ygimenez/Pagination-Utils/tree/2.1.2).
