### ISSUE TITLE
The first of two buttons does not work

### ISSUE THREAD

**Issue by Nick-kel** [ygimenez/Pagination-Utils#16]
**Checklist**
- [X] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [X] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [X] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [X] PaginationUtils is up-to-date.
- [X] You have activated the library as descripted in the README.

**Library info**
- JDA version 4.2.0_228
- PaginationUtils version 2.1.1

**Describe the bug**
If I add two bottuns in the success consumer of a message, the first button does not execute the consumer when reacting:
```
 Pages.buttonize(success, Collections.singletonMap("❌", deny), false, 120, TimeUnit.SECONDS);
 Pages.buttonize(success, Collections.singletonMap("✅", accept), false, 120, TimeUnit.SECONDS);
```
In this example, nothing happens when reacting with ❌. I also switched the order of the code lines and then the ✅ reaction didn't work.

**Comment by ygimenez** [comment]
That's because each message must have only one button listener attached to at any time.
To use multiple buttons on `buttonize` method, use a normal `Map` instead of a singleton, like the example below:

```java
Map<String, BiConsumer<Message, User>> buttons = new HashMap(){{
  put("❌", deny);
  put("✅", accept);
}};

Pages.buttonize(success, buttons, false, 120, TimeUnit.SECONDS);
```
