### ISSUE TITLE
No printed stack traces

### ISSUE THREAD

**Issue by Nick-kel** [ygimenez/Pagination-Utils#17]
**Checklist**
- [X] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [X] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [X] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [X] PaginationUtils is up-to-date.
- [X] You have activated the library as descripted in the README.

**Library info**
- JDA version 4.2.0_228
- PaginationUtils version 2.1.1

**Describe the bug**
If there's an error in the consumer (if you create a button, I only tested it with a button but the bug may occurs also if you paginate reactions) the stack trace won't be printed

**Comment by ygimenez** [comment]
Changed BiConsumers to ThrowingBiConsumers in [version 2.1.3](https://github.com/ygimenez/Pagination-Utils/releases/tag/2.1.3), this should make exceptions be printed in the logger when they occur inside them.
