### ISSUE TITLE
Cannot manually remove events from MessageHandler since update.

### ISSUE THREAD

**Issue by HeyBanditoz** [ygimenez/Pagination-Utils#18]
**Is your feature request related to a problem? Please describe.**
Previously, I was running version 1.3.0, which exposed Pages.handler so I could call removeEvent (in this case, it was when a user either won or lost a game). While updating Gradle dependencies, I noticed that version 2.1.2 doesn't appear to expose the handler anymore, or any way to remove an event.

**Describe the solution you'd like**
Either a getter to the handler, or a method in Pages to remove an event by a Message or an ID. I suppose having this method remove reactions already on the message would be neat, too.

**Describe alternatives you've considered**
None.

**Additional context**
You can check out [this code file](https://gitlab.com/HeyBanditoz/mchelper/-/blob/fd752379fad2834290d5479aba13a74a11e7312e/src/main/java/io/banditoz/mchelper/commands/BlackJackCommand.java) for how it was being done.

**Comment by ygimenez** [comment]
I'll put a getter to re-expose the handler again, thanks for pointing out.

**Comment by ygimenez** [comment]
Added a getter for `Pages.handler` in [version 2.1.3](https://github.com/ygimenez/Pagination-Utils/releases/tag/2.1.3)
