### ISSUE TITLE
setEmote doesn't work

### ISSUE THREAD

**Issue by avurro** [ygimenez/Pagination-Utils#19]
- PaginationUtils version 2.1.2

**Describe the bug**
I don't understand how to use setEmote for custom emojis, I get error whatever combination I try. Could you give me an example?

**Comment by ygimenez** [comment]
You need to pass the ID of the Emote, it can be found by putting \ behind it, it'll be in this format: <:name:**id**>

All you need to do after getting the mention is copy only the ID part of it.

**Comment by avurro** [comment]
have you done any tests about it? Because it does not work.

**Comment by ygimenez** [comment]
Yes I did test, what error are you getting? InvalidEmoteException?

**Comment by avurro** [comment]
Yes, with only ID doesn't work. It doesn't work with whatever combination of custom emoji identifiers

**Comment by ygimenez** [comment]
Could you show me how you're doing it?

In any case, I'll review it tomorrow to see if I find something, but that's really weird since I've tried it myself before releasing the version.

**Comment by avurro** [comment]
```java
Paginator paginator = PaginatorBuilder.createPaginator().setHandler(jda)
      .shouldRemoveOnReact(false)
      .setEmote(Emote.SKIP_BACKWARD,"807633784434327563")
      .setEmote(Emote.PREVIOUS,"809239881242247188")
      .setEmote(Emote.SKIP_FORWARD,"807633784580997130") 
      .setEmote(Emote.NEXT,"809239881141977098")
      .setEmote(Emote.CANCEL, "809239881002909737")
```
this is next button:
![image](https://user-images.githubusercontent.com/2487392/107595623-823bc400-6c15-11eb-8b35-8d5a3aa0329e.png)

**Comment by avurro** [comment]
However, even if it's not about this bug, the quick navigation arrows don't take custom emojis. As you can see from the test above. (with version 2.1.1.)

**Comment by ygimenez** [comment]
Those aren't SKIP buttons, those are GOTO buttons (GOTO_LAST and GOTO_FIRST).

About the ID issue, I'll double check it once I'm at my PC, I'll let you know about updates.

**Comment by ygimenez** [comment]
Could you be more specific on what error are you experiencing? I'm trying to reproduce it but everything seems normal (except for a Message retrieval error but this isn't related to what you reported).

**Comment by avurro** [comment]
![image](https://user-images.githubusercontent.com/2487392/107705459-0a29d880-6cbf-11eb-9cec-5c406950726c.png)

**Comment by ygimenez** [comment]
Are you sure your bot is in the server those emotes are in?
If you loop through those IDs won't any of those return null?

**Comment by avurro** [comment]
i'm sure because with version 2.1.1. it works. As you can see in screenshot in my previous comment https://github.com/ygimenez/Pagination-Utils/issues/19#issuecomment-777161032

(2.1.1. version code)
![image](https://user-images.githubusercontent.com/2487392/107707583-5fb3b480-6cc2-11eb-9735-edef2d3de4cf.png)

**Comment by avurro** [comment]
I don't understand why you want keep only id if JDA method take custom emoji with format "name:id". In 2.1.1. version, custom emoji are correctly loaded.

**Comment by ygimenez** [comment]
As I pointed before, by using `name + id` means that a single change in the Emote's name will invalidate your buttons, which doesn't happen when using only IDs

**Comment by avurro** [comment]
I understand this, but if the setReaction method asks for the custom emoji in the format "name: id" why not give it as it asked?

**Comment by ygimenez** [comment]
It doesn't ask in that format, it **gives** the option to use that format, addReaction has many signatures actually.

**Comment by avurro** [comment]
![image](https://user-images.githubusercontent.com/2487392/107711177-7e687a00-6cc7-11eb-904a-94b506793da8.png)
For custom emojis it's the only one.

**Comment by ygimenez** [comment]
You're looking at `addReaction(String)`, there's also `addReaction(Emote)`

**Comment by avurro** [comment]
![image](https://user-images.githubusercontent.com/2487392/107714540-c8545e80-6ccd-11eb-9be5-02fcf9c94c37.png)
For resource optimization reasons, I avoid using the cache as much as possible. CacheFlag.EMOTE is disabled in my case.

**Comment by avurro** [comment]
in case of a non-existent EMOTE, try using addReaction(String). It is a fair compromise.

**Comment by ygimenez** [comment]
That's the reason then, I'll try to see if there's any way to retrieve an Emote without using the cache.

About your suggestion, the issue isn't with addReaction but on how I retrieve the event from the handler, I can only use either the name or the ID of the Emote, not both.

**Comment by avurro** [comment]
![image](https://user-images.githubusercontent.com/2487392/107716111-01da9900-6cd1-11eb-8c59-4500bd3a7df5.png)
Same problem with getName. The best way is to switch the map key from EMOTE to String.

**Comment by ygimenez** [comment]
The map doesn't store Emote objects, it stores their IDs for comparison when pressing buttons. All I need to know is how can I retrieve an Emote without using the cache.

**Comment by ygimenez** [comment]
Found a way to retrieve Emotes without using the cache, the fix was added in [version 2.1.4](https://github.com/ygimenez/Pagination-Utils/releases/tag/2.1.4).
I'd still recommend using it tho, since it's generally faster while its footprint is really small even with thousands of Emotes.

**Comment by avurro** [comment]
Version 2.1.4:
```
[JDA RateLimit-Worker 2] WARN  net.dv8tion.jda.internal.requests.RateLimiter - Encountered 429 on route PUT/channels/{channel_id}/messages/{message_id}/reactions/{reaction_code}/{user_id} with bucket d6b7697c78814ecd72bb20df05517c78:guild_id:791430572387467286:webhook_id Retry-After: 235 ms
```
![image](https://user-images.githubusercontent.com/2487392/107849413-4c583480-6dfb-11eb-97db-06ea56b9fae1.png)

**Comment by avurro** [comment]
![image](https://user-images.githubusercontent.com/2487392/107855837-18920480-6e25-11eb-885c-222b959441a3.png)
After some tests I noticed 2 things:
  - the reactions do not reset after use, the page change action is performed when clicked, but the reaction remains clicked (same for categorize).
  - my bot works in the background writing, in the linked channels, any detection made. This writing speed probably compromises the library (in this version 2.1.4).

**Comment by ygimenez** [comment]
About first note, you've set `shouldRemoveOnReact` to false, so it'll not reset the reaction on click.
About the second note, I've not understood what you meant, could you reword it please?

Also, there's an issue that I've noticed when using cache-less clients (constantly hitting ratelimits), I'll look into it as soon as I can.

**Comment by ygimenez** [comment]
Please try the [latest release](https://github.com/ygimenez/Pagination-Utils/releases/tag/2.1.5), it should be working without hitting the ratelimits as it was before.

**Comment by avurro** [comment]
The library is much more responsive now, wow! Good Work! 👍

**Comment by ygimenez** [comment]
I'm happy your issue is solved, good coding!
