### ISSUE TITLE
Emotes occasionally appear with delay

### ISSUE THREAD

**Issue by avurro** [ygimenez/Pagination-Utils#20]
Pagination Utils 2.1.5

Emotes occasionally appear with delay

![image](https://user-images.githubusercontent.com/2487392/108356767-d550e080-71ec-11eb-9095-40a06de5120b.png)

After a while, the missing Emotes appear. It's not a blocking error but I still wanted to report it.

**Comment by ygimenez** [comment]
that's probably Discord ratelimiting something, afaik there's little we can do on our side.
