### ISSUE TITLE
It doesn't work in the private channel

### ISSUE THREAD

**Issue by avurro** [ygimenez/Pagination-Utils#21]
- [x] PaginationUtils is up-to-date.
- [x] You have activated the library as descripted in the README.

paginate/categorize doesn't work in private channels.
![image](https://user-images.githubusercontent.com/2487392/110403991-5843b900-807e-11eb-902e-51b1e39f1c2d.png)

there is something i forget?

**Comment by ygimenez** [comment]
Is removeOnReact disabled? Also, did you get any error in the console?

**Comment by avurro** [comment]
In my case i work with guilds and with private messages. 
and I prefer to keep:
`.shouldRemoveOnReact(true)`

Is there a possibility to differentiate between private messages and public messages?

**Comment by ygimenez** [comment]
it already does, but did you get any error at all?

**Comment by avurro** [comment]
I mean at the same time. I would like to keep TRUE for commands written in Guilds and FALSE for commands written privately to the bot.

**Comment by ygimenez** [comment]
I know, I asked if it was disabled because it affects the logic behind it, but still, is there any error I can use for reference?

**Comment by avurro** [comment]
I don't get any errors

**Comment by avurro** [comment]
In private channel the pagination doesn't work with any value I put (true/false) in shouldRemoveOnReact.

Am I wrong in something?

**Comment by ygimenez** [comment]
I'm currently solving some issues on my own bot, I'll see if I can find some issue on the library code later on.

**Comment by ygimenez** [comment]
Issue fixed in [release 2.1.6](https://github.com/ygimenez/Pagination-Utils/releases/tag/2.1.6)
