### ISSUE TITLE
Pagination not working in Slash Commands

### ISSUE THREAD

**Issue by aarondyejr** [ygimenez/Pagination-Utils#27]
**Checklist**

Make sure that you've checked all the items below.

- [x] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [ ] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [x] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [x] PaginationUtils is up-to-date.
- [x] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 757de9b
- PaginationUtils version 2.2.0

**Describe the bug**

When trying to use the pagination on an embed through slash commands I get 429 errors saying the reaction won't work.
I have tried countless times thinking it was my fault and it very well still could be but I have no idea what to change if it is so I am starting to think it is a bug.

**To Reproduce**

1. Follow the readme
2. Send the embed via:
```kotlin
event.hook.sendMessageEmbeds(...).queue { it ->
    Pages.pagination(it, myPages)
}
```
3. Call the slash command

**Expected behavior**

Well I expected it to react to the embed and work as normal.

**Screenshots**

![image](https://user-images.githubusercontent.com/54769204/120248305-6d6a5700-c22b-11eb-9840-2e642a4772f0.png)

**Additional context**

**Comment by ygimenez** [comment]
Do the reactions appear? That seems like you're getting ratelimited somewhere. Could you try on a private bot please?

**Comment by aarondyejr** [comment]
@ygimenez They do not appear at all and no matter on what bot I try it on the same thing happens.

**Comment by avurro** [comment]
Slash commands don't need gateway intents. In fact in the example reported on github the JDA configuration is the following ([SlashBotExample](https://github.com/DV8FromTheWorld/JDA/blob/development/src/examples/java/SlashBotExample.java)):
```java
JDABuilder.createLight(getBottoken(), EnumSet.noneOf(GatewayIntent.class))
```
If possible try to respect this configuration. (I am also interested in this development)

**Comment by ygimenez** [comment]
I'm rewriting the library to be compliant with the new features, including buttons and slash commands.

**Comment by avurro** [comment]
how's the work going ? do you have an alleged release date?

**Comment by ygimenez** [comment]
I've halted development for a while due to personal issues, but I'll return to it as soon as possible.

**Comment by sgoudham** [comment]
Has there been anymore work done on this?

**Comment by ygimenez** [comment]
For sure, you can check the latest commits to see what else was added, I'm just finishing polishing some rough edges before I release a new version.

**Comment by sgoudham** [comment]
Will the pagination now work through buttons in slash commands since you're not really able to get the message easily?

**Comment by ygimenez** [comment]
Both types of buttons will be supported, as for slashes all my tests paginate successfully as long as you passed a valid Message object (e.g: the reply message).

**Comment by sgoudham** [comment]
Ah okay, I was trying earlier to get a message object through slash commands and was unsuccessful. I hope you'll give some examples 😅 Aside from that, is there an ETA on this next release?

**Comment by ygimenez** [comment]
I don't know, maybe by next month or so

**Comment by sgoudham** [comment]
Looking forward to it!

**Comment by ygimenez** [comment]
Please check whether this issue still exists in latest version.

**Comment by ygimenez** [comment]
Considered fixed. Should it be required feel free to reopen the issue.
