### ISSUE TITLE
Depraction of PageType.EMBED

### ISSUE THREAD

**Issue by TheHolyFire** [ygimenez/Pagination-Utils#28]
Hey since PageType.EMBED is being deprecated i wanted to check what new method i should use since i didnt really understand the info in the givin Class

**Comment by ygimenez** [comment]
The newer method uses `instanceof` for checking what type of page it is, you don't need to supply any type anymore just the Message/MessageEmbed object.

**Comment by TheHolyFire** [comment]
Works like a charm
