### ISSUE TITLE
example is outdated

### ISSUE THREAD

**Issue by R-K-25** [ygimenez/Pagination-Utils#33]
**Checklist**

Make sure that you've checked all the items below.

- [*] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [*] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [*] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [*] PaginationUtils is up-to-date.
- [*] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 4.3
- PaginationUtils version 2.3.0

**Describe the bug**

readme example outdated and doest work

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ygimenez** [comment]
Are you referring to `master` branch's examples? They refer to the TBR version not the public release.

**Comment by ygimenez** [comment]
To prevent further mistakes I've moved current in-dev branch to nightly and restored master from latest public release.
