### ISSUE TITLE
Issues building project when added Pagination-Utils to JDA project

### ISSUE THREAD

**Issue by Maciox55** [ygimenez/Pagination-Utils#34]
**Checklist**

Make sure that you've checked all the items below.

- [X] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [ ] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [ ] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [X] PaginationUtils is up-to-date.
- [X] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 4.3.0_277
- PaginationUtils version 2.3.0

**Describe the bug**

When using Gradle and including the string from README.md
implementation group: 'com.github.ygimenez', name: 'Pagination-Utils', version: '2.3.0'

Gradle Build task errors out with the following:
`FAILURE: Build failed with an exception.

* What went wrong:
Gradle project fails to build due to a missing dependency of Pagination-Utils. When removed the project builds just fine. I was unable to find the liheyuan:simple-emoji dependency anywhere online.

`Execution failed for task ':lib:compileJava'.
> Could not resolve all files for configuration ':lib:compileClasspath'.
   > Could not find com.github.liheyuan:simple-emoji-4j:f26d3b39be.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/liheyuan/simple-emoji-4j/f26d3b39be/simple-emoji-4j-f26d3b39be.pom
       - https://m2.dv8tion.net/releases/com/github/liheyuan/simple-emoji-4j/f26d3b39be/simple-emoji-4j-f26d3b39be.pom
     Required by:
         project :lib > com.github.ygimenez:Pagination-Utils:2.3.0
`

**To Reproduce**

1. Steps to reproduce the behavior:
2. Add the Gradle dependency for Pagination-Utils as specified in README.md
    implementation group: 'com.github.ygimenez', name: 'Pagination-Utils', version: '2.3.0'

3. Build the project

**Expected behavior**

Application builds successfully after implementing all dependencies.

**Comment by Maciox55** [comment]
Shortly after I have realized that I needed to add to my gradle.build:
`maven { url 'https://jitpack.io' }`

It wasn't clear in the README.md at first.

**Comment by ygimenez** [comment]
Actually, the README.md was referring to in-dev version instead of the current public release (which depends on Simple Emoji), I've separated the project in two versions now (master and nightly) to prevent further mistakes.
