### ISSUE TITLE
Paginator reacts to every button even if it is already acknowleged

### ISSUE THREAD

**Issue by Miha23833** [ygimenez/Pagination-Utils#37]
**Checklist**

Make sure that you've checked all the items below.

- [x] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [x] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [x] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [x] PaginationUtils is up-to-date.
- [x] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 4.4.0_350
- PaginationUtils version 3.0.4

**Describe the bug**

When I update a self-written button that is not related to Paginator, I catch an exception from Paginator (attached). I think MessageHandler handles every buttonClick event even if it is acknowleged.

**To Reproduce**

1. Handle onButtonClick event in self-written ListenerAdapter;
2. Do anything with it to set Interatction of this event to **acknowleged**;
3. MessageHandler sends an exception because the message is already acknowleged

**Expected behavior**

MessageHandler should handle only its own onButtonClick events. 

**Additional context**

I believe you can differ buttons using customId and handle only yours.

[stacktrace.txt](https://github.com/ygimenez/Pagination-Utils/files/7900400/stacktrace.txt)

**Comment by ygimenez** [comment]
I see, I'll add some kind of tag to prevent interference with external events. Thanks for noticing that.

**Comment by ygimenez** [comment]
Issue fixed in [release 3.0.6](https://github.com/ygimenez/Pagination-Utils/tree/3.0.6)
