### ISSUE TITLE
Issue with pagination utils on jda 5.0.0

### ISSUE THREAD

**Issue by BlitzOffline** [ygimenez/Pagination-Utils#38]
**Checklist**

Make sure that you've checked all the items below.

- [x] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [x] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [x] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [x] PaginationUtils is up-to-date.
- [x] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 5.0.0-alpha.5
- PaginationUtils version 3.0.6

**Describe the bug**

There's an error on startup which probably has to do with the major changes JDA v5 is going thru. I was wondering if there is a way to get a development build or anything like that, that works with JDA 5 or are you guys waiting for JDA 5 to get out of alpha before updating it. The error log: https://www.toptal.com/developers/hastebin/uzecoxegiz

**To Reproduce**

1. Get JDA 5.0.0 alpha.5
2. Get Pagination-Utils 3.0.6
3. Use PaginatorBuilder.createPaginator()

**Comment by ygimenez** [comment]
JDA 5 is still in alpha version, so things are expected to break until they make an official release.

I'll refrain from releasing versions to make it compatible with it due to how volatile alpha phase is (things might change completely without warning). Sorry for the inconvenience, but a fix isn't feasible at the moment.

**Comment by BlitzOffline** [comment]
Yeah I am aware. I was just hoping that maybe you guys would make an alpha branch or something. I just forked it and made my own tho. I can PR to a different branch than the main if you guys want. I am aware that v5 gets quite a few breaking changes still.

If you guys want me to PR, just let me know with a reply here. will close the issue tho.

**Comment by ygimenez** [comment]
If your changes stay working after the full release I'll be happy to merge it into master afterwards, thanks for it!
