### ISSUE TITLE
java.lang.NoClassDefFoundError when trying to use Pagination-Utils

### ISSUE THREAD

**Issue by tctfox** [ygimenez/Pagination-Utils#43]
**Checklist**

Make sure that you've checked all the items below.

- [x ] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [ x] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [ x] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [ x] PaginationUtils is up-to-date.
- [ ] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 5.0.0-alpha.9
- PaginationUtils version 3.0.8

**Describe the bug**

I get a "Exception in thread "main" java.lang.NoClassDefFoundError" the moment I try to register a paginate Object. I coded quite a bit now with jda and everything else works. Buttons work, reactions work and the bot reacts to everything. But I cannot get Pagination-Utils to work. 
I did install it via maven and there no errors are showing. (Here my pom.xml -> https://pastebin.com/inddSqjf )
Here the full error -> https://pastebin.com/w3ZvsGm8

I tried to reinstall the maven dependency and I tried several pom.xml which I found in the disocrd but the error is always the same. Else the bot works just fine

**Comment by ygimenez** [comment]
Pagination Utils isn't compatible with JDA 5 yet (waiting for a stable release - See PR #39), you could use [BlitzOffline's fork](https://jitpack.io/#BlitzOffline/Pagination-Utils/-SNAPSHOT) as a quick fix for now.

**Comment by tctfox** [comment]
> Pagination Utils isn't compatible with JDA 5 yet (waiting for a stable release - See PR #39), you could use [BlitzOffline's fork](https://jitpack.io/#BlitzOffline/Pagination-Utils/-SNAPSHOT) as a quick fix for now.

thanks for the quick reply
The error is still here also with this fork. So it might be something else having to do with my project structure or something
but thanks for the help

**Comment by ygimenez** [comment]
Maybe they changed yet another thing in latest releases, which broke the fork too. You could try recompiling the library and replacing broken imports, that should solve the issue for now.

That's the very reason why I'm waiting for a full release before updating the library, `alpha` releases are usually very volatile and change quite often.

**Comment by st30611** [comment]
> > Pagination Utils isn't compatible with JDA 5 yet (waiting for a stable release - See PR #39), you could use [BlitzOffline's fork](https://jitpack.io/#BlitzOffline/Pagination-Utils/-SNAPSHOT) as a quick fix for now.
> 
> thanks for the quick reply The error is still here also with this fork. So it might be something else having to do with my project structure or something but thanks for the help

Just FYI, If you use the build off jitpack that's older (e.g. closer to when BlitzOffline made their CL changes for 5.0 compatibility), it should work: https://jitpack.io/#BlitzOffline/Pagination-Utils/-df18cc80e1-1

I used a jar from jitpack and managed to get it to work with 5.0.0-alpha9.
