### ISSUE TITLE
Unhandled exception when activating library

### ISSUE THREAD

**Issue by ghost** [ygimenez/Pagination-Utils#44]
**Checklist**

Make sure that you've checked all the items below.

- [x] Bot has the following permissions:
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [x] If using `JDABuilder.createLight()`, you added the following gateway intents:
    - GUILD_MESSAGES
    - GUILD_MESSAGE_REACTIONS
- [x] If using `.setRemoveOnReact(true)`, you have the following permission:
    - MESSAGE_MANAGE
- [x] PaginationUtils is up-to-date.

**Library info**

What libraries versions are you using.
- JDA version 4.3.0_333
- PaginationUtils version 3.0.8

**Describe the bug**

When activating the paginator, it gives me an UnhandledException due to InvalidHandlerException. When attempting to either add an exception to the method signature or surrounding with a try-catch, it gives me another error stating that the provided type is void. 

Edit note: These errors appear in the IDE rather than the console. Won't let me start the bot.

**Comment by ygimenez** [comment]
Didn't have time to answer yet, but you're probably doing other operations before declaring a handler.

The error happens because the library needs the handler (either JDA or ShardManager) to be able to check for Emotes' validity.

**Comment by ghost** [comment]
> Didn't have time to answer yet, but you're probably doing other operations before declaring a handler.
> 
> The error happens because the library needs the handler (either JDA or ShardManager) to be able to check for Emotes' validity.

Yeah, after sleeping I, unfortunately, realised the issue.
