### ISSUE TITLE
I need a usage example

### ISSUE THREAD

**Issue by avurro** [ygimenez/Pagination-Utils#7]
**Checklist**

Make sure that you've checked all the items below.

- [X] Bot has the following permissions:
  - MESSAGE_MANAGE
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [X] PaginationUtils is up-to-date.
- [X] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 4.2.0_181
- PaginationUtils version 2.0.0

**Describe the bug**

I can't in any way to make the pagination. Not even copying and pasting the code in README. Could you please write me a complete whole code?

**Expected behavior**

A complete sample code that I can copy and paste

**Comment by ygimenez** [comment]
Could you show me how you're doing it?
Also, what kind of issues are you having?

**Comment by avurro** [comment]
Only the first page appears, the buttons do not appear.
Code follows:
```java
List<Page> pages = new ArrayList<>();
for (Entry<String, List<Class<?>>> page : this.commandsCategory.entrySet())
	pages.add(makePage(event, page.getKey(), page.getValue()));
		
event.getChannel().sendMessage((Message) pages.get(0).getContent()).queue(success -> {
		    Pages.paginate(success, pages, 60, TimeUnit.SECONDS);
});

private Page makePage(MessageReceivedEvent event, String category, List<Class<?>> commandsClasses) {
		
	MessageBuilder eb = new MessageBuilder();
	eb.setContent("text");
	return new Page(PageType.TEXT, eb.build());
}
```
In Main:
```java
public static void main(String[] args){
   ...    	
   try {
            jda = JDABuilder.createLight(getBottoken(), GatewayIntent.GUILD_MESSAGES)
                    .addEventListeners(new MessageListener())
                    .build();
            jda.awaitReady();
            Pages.activate(jda);
   } catch (LoginException e) {
   ...
```

**Comment by avurro** [comment]
Can you please just write me a complete working piece of code?

**Comment by ygimenez** [comment]
Your code is correct, do you get any error in the console? 
If you use EmbedBuilder instead of MessageBuilder does it work?

**Comment by avurro** [comment]
Same result with EmbedBuilder.
Can you please just write me a complete working piece of code that I can copy and paste?

**Comment by ygimenez** [comment]
Does this work? Please check the console for any error. 
```java
List<Page> pages = new ArrayList<>();

EmbedBuilder eb = new EmbedBuilder();
for (int i = 0; i < 5; i++) {
	eb.setDescription("Test " + i);
	pages.add(new Page(PageType.EMBED, eb.build()));
} 

event.getChannel().sendMessage((MessageEmbed) pages.get(0).getContent()).queue(s -> {
	Pages.paginate(s, pages, 60, TimeUnit.SECONDS);
});
```

**Comment by avurro** [comment]
![image](https://user-images.githubusercontent.com/2487392/103464015-09ea0500-4d31-11eb-98e7-8801e78225c0.png)
Are you sure your code works?
Can you try it yourself please?

**Comment by ygimenez** [comment]
Did it work? I'll close this issue if no reply is supplied.

**Comment by ygimenez** [comment]
It does work, I use it exactly like that in my bot's code, are you sure you have all the required permissions?
Could you please check if no exception were thrown in the console?

**Comment by avurro** [comment]
No exceptions are thrown, it just doesn't work.
Can you show me how you set up JDA?

> are you sure you have all the required permissions?

My bot has admin permissions

**Comment by avurro** [comment]
I finally understood what the problem is, the bot must have the following explicit intentions:
```
GatewayIntent.GUILD_MESSAGES
GatewayIntent.GUILD_MESSAGE_REACTIONS
```
I am using `JDABuilder.createLight` and these permissions are not set by default as is the case with `JDABuilder.createDefault` which is what you probably use.

You should make this explicit in the documentation.

**Comment by ygimenez** [comment]
Honesty I didn't know createLight removed such basic intents, I'll add a note about it next to required permissions.
Thanks for pointing out the solution.
